<?php

namespace StarkInfra\PixInternalTransactionReport;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\PixInternalTransactionReport;


class Log extends Resource
{

    public $report;
    public $type;
    public $errors;
    public $created;

    /**
    # PixInternalTransactionReport\Log object

    Every time a PixInternalTransactionReport entity is modified, a corresponding
    PixInternalTransactionReport\Log is generated for the entity. This log is never
    generated by the user.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - report [PixInternalTransactionReport]: PixInternalTransactionReport entity to which the log refers to.
        - type [string]: type of the PixInternalTransactionReport event which triggered the log creation. ex: "created", "failed", "sent", "success"
        - errors [array of strings]: array of errors linked to this PixInternalTransactionReport event.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this-> report = Checks::checkParam($params, "report");
        $this-> type = Checks::checkParam($params, "type");
        $this-> errors = Checks::checkParam($params, "errors");
        $this-> created = Checks::checkDateTime(Checks::checkParam($params, "created"));

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific PixInternalTransactionReport\Log

    Receive a single PixInternalTransactionReport\Log object previously created by the Stark Infra API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - PixInternalTransactionReport\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve PixInternalTransactionReport\Logs

    Receive an enumerator of PixInternalTransactionReport\Log objects previously created in the Stark Infra API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null]: date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null]: date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter retrieved objects by types. ex: ["success", "failed"]
        - reportIds [array of strings, default null]: array of PixInternalTransactionReport ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of PixInternalTransactionReport\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged PixInternalTransactionReport\Logs

    Receive a list of up to 100 PixInternalTransactionReport\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null]: date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null]: date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter retrieved objects by types. ex: ["success", "failed"]
        - reportIds [array of strings, default null]: list of PixInternalTransactionReport ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was set before function call

    ## Return:
        - list of PixInternalTransactionReport\Log objects with updated attributes
        - cursor to retrieve the next page of PixInternalTransactionReport\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $reportLog = function ($array) {
            $report = function ($array) {
                return new PixInternalTransactionReport($array);
            };
            $array["report"] = API::fromApiJson($report, $array["report"]);
            return new Log($array);
        };
        return [
            "name" => "PixInternalTransactionReportLog",
            "maker" => $reportLog,
        ];
    }
}
