<?php

namespace StarkInfra\PixPullSubscription;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\PixPullSubscription;


class Log extends Resource
{

    public $subscription;
    public $type;
    public $errors;
    public $created;

    /**
    # PixPullSubscription\Log object

    Every time a PixPullSubscription entity is modified, a corresponding PixPullSubscription\Log
    is generated for the entity. This log is never generated by the user.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created.
        - subscription [PixPullSubscription]: PixPullSubscription entity to which the log refers to.
        - type [string]: type of the PixPullSubscription event which triggered the log creation.
        - errors [array of strings]: list of errors linked to this PixPullSubscription event.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this-> subscription = Checks::checkParam($params, "subscription");
        $this-> type = Checks::checkParam($params, "type");
        $this-> errors = Checks::checkParam($params, "errors");
        $this-> created = Checks::checkDateTime(Checks::checkParam($params, "created"));

        Checks::checkParams($params);
    }

    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $subscriptionLog = function ($array) {
            $subscription = function ($array) {
                return new PixPullSubscription($array);
            };
            $array["subscription"] = API::fromApiJson($subscription, $array["subscription"]);
            return new Log($array);
        };
        return [
            "name" => "PixPullSubscriptionLog",
            "maker" => $subscriptionLog,
        ];
    }
}
