<?php

namespace StarkInfra\PixPullSubscription;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\PixPullSubscription;


class Log extends Resource
{

    public $subscription;
    public $type;
    public $errors;
    public $created;

    /**
    # PixPullSubscription\Log object

    Every time a PixPullSubscription entity is modified, a corresponding PixPullSubscription\Log
    is generated for the entity. This log is never generated by the user, but it can be
    retrieved to check additional information on the PixPullSubscription.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - subscription [PixPullSubscription]: PixPullSubscription entity to which the log refers to.
        - type [string]: type of the PixPullSubscription event which triggered the log creation. Options: "created", "delivering", "delivered", "failed", "approved", "denied", "confirmed", "expired", "canceling", "canceled".
        - errors [array of maps]: list of errors linked to this PixPullSubscription event. Each error is a map with "code" and "message" keys. ex: [["code" => "userRejected", "message" => "subscription was rejected by the sender"]]
        - created [DateTime]: creation datetime for the log. ex: "2026-04-03T12:00:00+00:00"
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this-> subscription = Checks::checkParam($params, "subscription");
        $this-> type = Checks::checkParam($params, "type");
        $this-> errors = Checks::checkParam($params, "errors");
        $this-> created = Checks::checkDateTime(Checks::checkParam($params, "created"));

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific PixPullSubscription\Log

    Receive a single PixPullSubscription\Log object previously created by the Stark Infra API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - PixPullSubscription\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve PixPullSubscription\Logs

    Receive an enumerator of PixPullSubscription\Log objects previously created in the Stark Infra API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null]: date filter for objects created only after specified date. ex: "2026-04-03"
        - before [Date or string, default null]: date filter for objects created only before specified date. ex: "2026-04-03"
        - types [array of strings, default null]: filter for log event types. Options: "created", "delivering", "delivered", "failed", "approved", "denied", "confirmed", "expired", "canceling", "canceled".
        - subscriptionIds [array of strings, default null]: array of PixPullSubscription ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of PixPullSubscription\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged PixPullSubscription\Logs

    Receive a list of up to 100 PixPullSubscription\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null]: date filter for objects created only after specified date. ex: "2026-04-03"
        - before [Date or string, default null]: date filter for objects created only before specified date. ex: "2026-04-03"
        - types [array of strings, default null]: filter for log event types. Options: "created", "delivering", "delivered", "failed", "approved", "denied", "confirmed", "expired", "canceling", "canceled".
        - subscriptionIds [array of strings, default null]: array of PixPullSubscription ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - list of PixPullSubscription\Log objects with updated attributes
        - cursor to retrieve the next page of PixPullSubscription\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $subscriptionLog = function ($array) {
            $subscription = function ($array) {
                return new PixPullSubscription($array);
            };
            $array["subscription"] = API::fromApiJson($subscription, $array["subscription"]);
            return new Log($array);
        };
        return [
            "name" => "PixPullSubscriptionLog",
            "maker" => $subscriptionLog,
        ];
    }
}
