<?php

namespace StarkInfra\Ledger;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\Ledger;


class Log extends Resource
{

    public $created;
    public $type;
    public $errors;
    public $ledger;

    /**
    # Ledger\Log object

    Every time a Ledger entity is updated, a corresponding Ledger\Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the Ledger.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - type [string]: type of the Ledger event which triggered the log creation. ex: "created", "updated"
        - errors [array of strings]: array of errors linked to this Ledger event
        - ledger [Ledger]: Ledger entity to which the log refers to.
        - created [DateTime]: creation datetime for the log.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->ledger = Checks::checkParam($params, "ledger");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific Ledger\Log

    Receive a single Ledger\Log object previously created by the Stark Infra API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - Ledger\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve Ledger\Logs

    Receive an enumerator of Ledger\Log objects previously created in the Stark Infra API

    ## Parameters (optional):
        - ids [array of strings, default null]: list of Log ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - ledgerId [string, default null]: filter logs by Ledger id. ex: "5656565656565656"
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of Ledger\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged Ledger\Logs

    Receive a list of up to 100 Ledger\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - ids [array of strings, default null]: list of Log ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - ledgerId [string, default null]: filter logs by Ledger id. ex: "5656565656565656"
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - list of Ledger\Log objects with updated attributes
        - cursor to retrieve the next page of Ledger\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $ledgerLog = function ($array) {
            $ledger = function ($array) {
                return new Ledger($array);
            };
            $array["ledger"] = API::fromApiJson($ledger, $array["ledger"]);
            return new Log($array);
        };
        return [
            "name" => "LedgerLog",
            "maker" => $ledgerLog,
        ];
    }
}
