<?php

namespace StarkInfra;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;


class IssuingHolder extends Resource
{
    /**
    # IssuingHolder object

    The IssuingHolder object displays the informations of Cards created to your Workspace.

    ## Parameters (required):
        - name [string]: card holder name. ex: "Tony Stark"
        - taxId [string]: card holder tax ID. ex: "012.345.678-90"
        - externalId [string] card holder unique id, generated by the user to avoid duplicated holders. ex: "my-entity/123"

    ## Parameters (optional):
        - rules [array of IssuingRule, default []]: [EXPANDABLE] list of holder spending rules.
        - tags [array of strings, default []]: list of strings for tagging. ex: ["travel", "food"]

    ## Attributes (return-only):
        - id [string]: unique id returned when IssuingHolder is created. ex: "5656565656565656"
        - status [string]: current IssuingHolder status. ex: "canceled" or "active"
        - created [DateTime]: creation datetime for the IssuingHolder. 
        - updated [DateTime]: latest update datetime for the IssuingHolder. 
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->name = Checks::checkParam($params, "name");
        $this->taxId = Checks::checkParam($params, "taxId");
        $this->externalId = Checks::checkParam($params, "externalId");
        $this->rules = IssuingRule::parseRules(Checks::checkParam($params, "rules"));
        $this->tags = Checks::checkParam($params, "tags");
        $this->status = Checks::checkParam($params, "status");
        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->updated = Checks::checkDateTime(Checks::checkParam($params, "updated"));

        Checks::checkParams($params);
    }

    /**
    # Create IssuingHolder

    Send a list of IssuingHolder objects for creation in the Stark Infra API

    ## Parameters (required):
        - holders [array of IssuingHolder objects]: list of IssuingHolder objects to be created in the API

    ## Parameters (optional):
        - params [dictionary of optional parameters]:
            - expand [array of strings, default null]: fields to to expand information. ex: ["rules"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - list of IssuingHolder objects with updated attributes
     */
    public static function create($holders, $params = null, $user = null)
    {
        return Rest::post($user, IssuingHolder::resource(), $holders, $params);
    }

    /**
    # Retrieve a specific Holder

    Receive a single IssuingHolder object previously created in the Stark Infra API by its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - params [dictionary of optional parameters]:
            - expand [array of strings, default []]: fields to to expand information. ex: ["rules", "securityCode", "number", "expiration"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - IssuingHolder object with updated attributes
     */
    public static function get($id, $param = null, $user = null)
    {
        return Rest::getId($user, IssuingHolder::resource(), $id, $param);
    }

    /**
    # Retrieve IssuingHolders

    Receive an enumerator of IssuingHolder objects previously created in the Stark Infra API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. 
        - before [Date or string, default null] date filter for objects created only before specified date. 
        - status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"
        - tags [array of strings, default null]: tags to filter retrieved objects. ex: ["tony", "stark"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - expand [array of strings, default []]: fields to to expand information. ex: ["rules", "securityCode", "number", "expiration"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of IssuingHolder objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, IssuingHolder::resource(), $options);
    }

    /**
    # Retrieve paged Holders

    Receive a list of IssuingHolder objects previously created in the Stark Infra API and the cursor to the next page.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"
        - tags [array of strings, default null]: tags to filter retrieved objects. ex: ["tony", "stark"]
        - ids [array of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - expand [array of strings, default []]: fields to to expand information. ex: ["rules", "securityCode", "number", "expiration"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call
    
    ## Return:
        - list of IssuingHolder objects with updated attributes
        - cursor to retrieve the next page of IssuingHolder objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, IssuingHolder::resource(), $options);
    }

    /**
    # Update IssuingHolder entity

    Update IssuingHolder by passing id.

    ## Parameters (required):
        - id [array of strings]: IssuingHolder unique ids. ex: "5656565656565656"

    ## Parameters (optional):
        - status [string, default null]: You may block the IssuingHolder by passing 'blocked' in the status
        - name [string, default null]: card holder name. ex: "Tony Stark"
        - tags [array of strings, default null]: list of strings for tagging. ex: ["tony", "stark"]
        - rules [array of dictionaries, default null]: list of dictionaries with "amount": int, "currencyCode": string, "id": string, "interval": string, "name": string pairs
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - target IssuingHolder with updated attributes
     */
    public static function update($id, $options = [], $user = null)
    {
        return Rest::patchId($user, IssuingHolder::resource(), $id, $options);
    }

    /**
    # Cancel an IssuingHolder entity

    Cancel an IssuingHolder entity previously created in the Stark Infra API

    ## Parameters (required):
        - id [string]: IssuingHolder unique id. ex: "5656565656565656"
    
    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call
    
    ## Return:
        - canceled IssuingHolder object
     */
    public static function cancel($id, $user = null)
    {
        return Rest::deleteId($user, IssuingHolder::resource(), $id);
    }

    private static function resource()
    {
        $holder = function ($array) {
            return new IssuingHolder($array);
        };
        return [
            "name" => "IssuingHolder",
            "maker" => $holder,
        ];
    }
}
