<?php

namespace StarkInfra\IssuingToken;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\IssuingToken;


class Log extends Resource
{

    public $token;
    public $type;
    public $errors;
    public $created;

    /**
    # IssuingToken\Log object

    Every time an IssuingToken entity is updated, a corresponding IssuingToken\Log
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the IssuingToken.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - token [IssuingToken]: IssuingToken entity to which the log refers to.
        - errors [array of strings]: list of errors linked to this IssuingToken event
        - type [string]: type of the IssuingToken event which triggered the log creation. ex: "active", "blocked", "canceled", "frozen" or "pending"
        - created [DateTime]: creation datetime for the IssuingToken. 
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this->token = Checks::checkParam($params, "token");
        $this->type = Checks::checkParam($params, "type");
        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this->errors = Checks::checkParam($params, "errors");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific IssuingToken\Log

    Receive a single IssuingToken\Log object previously created in the Stark Infra API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - IssuingToken\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve IssuingToken\Logs

    Receive an enumerator of IssuingToken\Log objects previously created in the Stark Infra API

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter for log event types. ex: "active", "blocked", "canceled", "frozen", "pending"
        - tokenIds [array of strings, default null]: array of IssuingToken ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - ids [list of strings, default null]: array of IssuingToken ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of IssuingToken\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged IssuingToken\Logs

    Receive a list of up to 100 IssuingToken\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter for log event types. ex: "active", "blocked", "canceled", "frozen", "pending"
        - tokenIds [array of strings, default null]: array of IssuingToken ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - ids [list of strings, default null]: array of IssuingToken ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call
    
    ## Return:
        - list of IssuingToken\Log objects with updated attributes
        - cursor to retrieve the next page of IssuingToken\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $tokenLog = function ($array) {
            $token = function ($array) {
                return new IssuingToken($array);
            };
            $array["token"] = API::fromApiJson($token, $array["token"]);
            return new Log($array);
        };
        return [
            "name" => "IssuingTokenLog",
            "maker" => $tokenLog,
        ];
    }
}
