<?php

namespace StarkInfra\IndividualAccountAttachment;
use StarkCore\Utils\API;
use StarkInfra\Utils\Rest;
use StarkCore\Utils\Checks;
use StarkCore\Utils\Resource;
use StarkCore\Utils\StarkDate;
use StarkInfra\IndividualAccountAttachment;


class Log extends Resource
{

    public $attachment;
    public $type;
    public $errors;
    public $created;

    /**
    # IndividualAccountAttachment\Log object

    Every time an IndividualAccountAttachment entity is updated, a corresponding
    IndividualAccountAttachment\Log is generated for the entity. This log is never
    generated by the user, but it can be retrieved to check additional information
    on the IndividualAccountAttachment.

    ## Attributes (return-only):
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - attachment [IndividualAccountAttachment]: IndividualAccountAttachment entity to which the log refers to.
        - errors [array of strings]: array of errors linked to this IndividualAccountAttachment event
        - type [string]: type of the IndividualAccountAttachment event which triggered the log creation. Options: "created", "success", "failed", "deleted"
        - created [DateTime]: creation datetime for the log.
     */

    function __construct(array $params)
    {
        parent::__construct($params);

        $this->attachment = Checks::checkParam($params, "attachment");
        $this->type = Checks::checkParam($params, "type");
        $this->errors = Checks::checkParam($params, "errors");
        $this->created = Checks::checkDateTime(Checks::checkParam($params, "created"));

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific IndividualAccountAttachment\Log

    Receive a single IndividualAccountAttachment\Log object previously created by the Stark Infra API by passing its id

    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"

    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - IndividualAccountAttachment\Log object with updated attributes
     */
    public static function get($id, $user = null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve IndividualAccountAttachment\Logs

    Receive an enumerator of IndividualAccountAttachment\Log objects previously created in the Stark Infra API.
    Use this function instead of page if you want to stream the objects without worrying about cursors and pagination.

    ## Parameters (optional):
        - limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter for log event types. ex: ["created", "success", "failed", "deleted"]
        - attachmentIds [array of strings, default null]: array of IndividualAccountAttachment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - enumerator of IndividualAccountAttachment\Log objects with updated attributes
     */
    public static function query($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));

        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged IndividualAccountAttachment\Logs

    Receive a list of up to 100 IndividualAccountAttachment\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.

    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [array of strings, default null]: filter for log event types. ex: ["created", "success", "failed", "deleted"]
        - attachmentIds [array of strings, default null]: array of IndividualAccountAttachment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkInfra\Settings::setUser() was used before function call

    ## Return:
        - list of IndividualAccountAttachment\Log objects with updated attributes
        - cursor to retrieve the next page of IndividualAccountAttachment\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));

        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $attachmentLog = function ($array) {
            $individualAccountAttachment = function ($array) {
                return new IndividualAccountAttachment($array);
            };
            $array["attachment"] = API::fromApiJson($individualAccountAttachment, $array["attachment"]);
            return new Log($array);
        };
        return [
            "name" => "IndividualAccountAttachmentLog",
            "maker" => $attachmentLog,
        ];
    }
}
