<?php

namespace StarkInfra\PixInfraction;
use StarkInfra\PixInfraction;
use StarkInfra\Utils\Checks;
use StarkInfra\Utils\Resource;
use StarkInfra\Utils\Rest;
use StarkInfra\Utils\API;
use StarkInfra\Utils\StarkDate;


class Log extends Resource
{
    /**
    # PixInfraction\Log object

    Every time a PixInfraction entity is modified, a corresponding PixInfraction\Log
    is generated for the entity. This log is never generated by the user.
    
    ## Attributes:
        - id [string]: unique id returned when the log is created. ex: "5656565656565656"
        - created [Date, Datetime or string]: creation datetime for the log. ex: "2020-03-10 10:30:00.000"
        - type [string]: type of the PixInfraction event which triggered the log creation. ex: "created", "failed", "delivering", "delivered", "closed", "canceled".
        - errors [list of strings]: list of errors linked to this PixInfraction event
        - infraction [PixInfraction]: PixInfraction entity to which the log refers to.
     */
    function __construct(array $params)
    {
        parent::__construct($params);

        $this-> created = Checks::checkDateTime(Checks::checkParam($params, "created"));
        $this-> type = Checks::checkParam($params, "type");
        $this-> errors = Checks::checkParam($params, "errors");
        $this-> infraction = Checks::checkParam($params, "infraction");

        Checks::checkParams($params);
    }

    /**
    # Retrieve a specific PixInfraction\Log

    Receive a single PixInfraction\Log object previously created by the Stark Infra API by its id
    
    ## Parameters (required):
        - id [string]: object unique id. ex: "5656565656565656"
    
    ## Parameters (optional):
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkinfra\user was set before function call
    
    ## Return:
        - PixInfraction\Log object with updated attributes
    */
    public static function get($id, $user=null)
    {
        return Rest::getId($user, Log::resource(), $id);
    }

    /**
    # Retrieve PixInfraction\Logs

    Receive a generator of PixInfraction\Log objects previously created in the Stark Infra API
    
    ## Parameters (optional):
        - ids [list of strings, default null]: Log ids to filter PixInfraction Logs. ex: ["5656565656565656"]
        - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [list of strings, default null]: filter retrieved objects by types. ex: "created", "failed", "delivering", "delivered", "closed", "canceled".
        - infractionsIds [list of strings, default null]: list of PixInfraction IDs to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkinfra\user was set before function call
    
    ## Return:
        - generator of PixInfraction\Log objects with updated attributes
     */
    public static function query($options=[], $user=null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
    
        return Rest::getList($user, Log::resource(), $options);
    }

    /**
    # Retrieve paged PixInfraction\Logs

    Receive a list of up to 100 PixInfraction\Log objects previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your reports.
    
    ## Parameters (optional):
        - cursor [string, default null]: cursor returned on the previous page function call
        - ids [list of strings, default null]: Log ids to filter PixInfraction Logs. ex: ["5656565656565656"]
        - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
        - after [Date or string, default null] date filter for objects created only after specified date. ex: "2020-04-03"
        - before [Date or string, default null] date filter for objects created only before specified date. ex: "2020-04-03"
        - types [list of strings, default null]: filter retrieved objects by types. ex:  "created", "failed", "delivering", "delivered", "closed", "canceled".
        - infractionIds [list of strings, default null]: list of PixInfraction ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        - user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkinfra\user was set before function call
    
    ## Return:
        - list of PixInfraction\Log objects with updated attributes
        - cursor to retrieve the next page of PixInfraction\Log objects
     */
    public static function page($options = [], $user = null)
    {
        $options["after"] = new StarkDate(Checks::checkParam($options, "after"));
        $options["before"] = new StarkDate(Checks::checkParam($options, "before"));
        
        return Rest::getPage($user, Log::resource(), $options);
    }

    private static function resource()
    {
        $infractionLog = function ($array) {
            $infraction = function ($array) {
                return new PixInfraction($array);
            };
            $array["infraction"] = API::fromApiJson($infraction, $array["infraction"]);
            return new Log($array);
        };
        return [
            "name" => "PixInfractionLog",
            "maker" => $infractionLog,
        ];
    }
}
